### ISSUE TITLE
Provide a package server for Debian packages

### ISSUE THREAD

**Issue by scheibel** [cginternals/globjects#190]
I searched several articles that explain the creation and maintenance of Debian package repositories.
- http://www.thomas-krenn.com/de/wiki/Eigenes_apt-Repository_mit_reprepro_unter_Ubuntu_erstellen
- http://www.pro-linux.de/artikel/2/1459/apt-repositorium-erstellen-variante-1-apt-ftparchive.html
- http://debiananwenderhandbuch.de/apt-ftparchive.html
- http://debian-handbook.info/browse/stable/sect.setup-apt-package-repository.html

The first one looks promising enough.
If we want to create such a repository and host it on one of our servers, we can provide (GPG verified) packages that can be used by Debian and Ubuntu distributions by the package managers apt, aptitute, synaptics and Ubuntu Software Center, at least.

I suggest a separation of glow into five separate packages plus the possibility to access the sources specific to the current available version.
- glow -> glow release libraries
- glow-dbg -> glow debug libraries
- glow-dev -> glow include headers (depends on glow or glow-dbg, not sure yet)
- glow-examples-data -> glow data (e.g. shaders)
- glow-examples-bin -> glow examples (depends on glow and glow-examples-data)

Additionally, the following meta-packages can be provided:
- glow-full (depends on all other glow packages)
- glow-examples (depends on glow-examples-data and glow-examples-bin)

For releases before Ubuntu 14.04 (and I think for all Debian releases) we have to additionally deploy packages for glew, glfw (as long as both are dependencies of glow) and glm, but that shouldn't be such a big deal.

**Comment by ghisvail** [comment]
[`reprepro`](https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro) is the solution everyone is using these days, and the one you are most likely to find support for if you query the Debian IRC channels or mailing lists.

> glow-dbg may be a problem, because cmake is not able to build both release and debug versions in one build.

Don't bother too much with the -dbg package, Debian now supports building them [automatically](https://wiki.debian.org/AutomaticDebugPackages).

**Comment by scheibel** [comment]
Although we don't use an own server to distribute the dpkg packages, I'll close this issue for now.
Currently we're happy with the Debian integration.
