### ISSUE TITLE
globjects::init(): print warning when overriding glbinding callback

### ISSUE THREAD

**Issue by mrzzzrm** [cginternals/globjects#298]
At the moment globjects::init() registers manualErrorCheckAfter()/manualContextCheck() as glbindings general After/BeforeCallback. The user (e.g.: me) might not expect this. Could you check for callbacks being set in globjects::init() before overriding them and print a warning in case the user has already set a callback?

**Comment by scheibel** [comment]
Seems reasonable. We will discuss solutions.
