### ISSUE TITLE
Usage of ref_ptr in Framebuffer Attachments

### ISSUE THREAD

**Issue by wobakj** [cginternals/globjects#313]
The documentation advises to use reference pointers to store all globjects pointers. On the other hand, in some examples and in the snippets in the documentation raw pointers are used. 
At first this lead me to believe that the reference pointers are only necessary when one object has multiple owners and raw pointers without manual reference taking are enough if only one owner exists. (similar to using shared pointers only when multiple owners exist)

Using normal pointers for the objects worked as expected except for the textures.
The AttachedTexture and -Renderbuffer classes store the Texture/Renderbuffer in a reference pointer. This leads to the deletion of the object at detachment if no reference has been taken anywhere else. 

Of course it is much more comfortable to have a reference pointer even for a sole owner due to the automatic object deallocation.
However I am still wondering whether reference counting is either mandatory and the ref_ptr member a design decision or if it is only advised and the member should be a raw pointer.

**Comment by scheibel** [comment]
Reference counting is mandatory in globjects.
However, using reference pointers (```ref_ptr```) is not.
You may call ```ref()``` and ```unref()``` by yourself if you store a pointer to an object and release it later.
See here: https://github.com/cginternals/globjects#reference-pointers

Some code snippets you see are simplified to focus on some specific aspect. In our actual examples, you should not see plain pointers.

There are some exceptions where we don't use reference pointers in the globjects library. The exception is only when the reference pointer is a back reference to an object that holds a reference pointer to the first object. This should circumvent cyclic dependencies in which case an object will never be freed.
