### ISSUE TITLE
Make tests a standalone CMake project

### ISSUE THREAD

**Issue by ghisvail** [cginternals/globjects#344]
Could you guys repeat the same setup for making the test suite of `globjects` standalone like for [`glbinding`](https://github.com/cginternals/glbinding/blob/master/source/tests/CMakeLists.txt)?

**Comment by scheibel** [comment]
We will.

**Comment by scheibel** [comment]
Do you wish this for the current master version only (which is not interface-compatible to globjects 1.x and thus, will be released as globjects 2.0 in the following months) or do you want a backport to the 1.1.x release as well?

**Comment by ghisvail** [comment]
Debian is in freeze at the moment, so I can wait a few months. Thanks.

**Comment by scheibel** [comment]
The current master provides the tests as separate cmake project.
If anything regarding the external testing doesn't work you can add the issues here.
