### ISSUE TITLE
glVertexArrayElementBuffer for VertexArray

### ISSUE THREAD

**Issue by itsuhane** [cginternals/globjects#346]
Currently, to use index buffer object, one has to manually bind VAO then bind IBO with `GL_ELEMENT_ARRAY_BUFFER`:
```
vao->bind();
// :::
ibo->bind(gl::GL_ELEMENT_ARRAY_BUFFER);
// :::
vao->unbind();
```

In OpenGL 4.5, `glVertexArrayElementBuffer` was introduced as a part of DSA. `VertexArray` should add an interface, `setIndexBuffer` for example, to support this. In this case, one could write:
```
// :::
vao->setIndexBuffer(ibo);
// :::
```
without explicitly bind/unbind VAO. This should make the program logically more clear and consistent.

Without DSA, this new interface could be emulated as
```
void VertexArray::setIndexBuffer(Buffer *ibo) {
    bind();
    ibo->bind(gl::GL_ELEMENT_ARRAY_BUFFER);
}
```

**Comment by scheibel** [comment]
Seems like I have missed this function while integrating the DSA strategies.
I'll provide an example implementation for testing.
