### ISSUE TITLE
Sampler::setParameter cannot take vector value

### ISSUE THREAD

**Issue by itsuhane** [cginternals/globjects#350]
Sampler class doesn't implement interface for `glSamplerParameter[if]v` and `glSamplerParameterI[i ui]v`.

I was trying to set `GL_TEXTURE_BORDER_COLOR`, which is impossible with Sampler.

**Comment by scheibel** [comment]
I opened a PR adding the interface to set 4-component vectors of type float, int or unsigned int as parameter values on a Sampler (#351).
This should suffice to set the texture border color on a sampler.
