### ISSUE TITLE
Bug in Texture::cubeMapImage

### ISSUE THREAD

**Issue by scheibel** [cginternals/globjects#368]
In each implementation of `Texture::cubeMapImage` loads the first of all six cube map part into all cube map layers.
I imagine users of `cubeMapImage` provide one cube map part for each layer (totalling to six).

**Comment by dlyr** [comment]
I confirm this bug, we actually load cubemaps images using raw opengl calls.
It would be nice (and easy) to take an array of 6 data ptr to set the 6 images.

**Comment by dlyr** [comment]
I can do a PR that uses data[i] instead of data, if data is not nullptr.
Is that ok ?

**Comment by scheibel** [comment]
Thanks for the offer, but I'll rather go with a function overload taking an array of 6 data pointers.
