### ISSUE TITLE
Framebuffer::detach() : Fails for attachmentObject->isRenderBufferAttachment()

### ISSUE THREAD

**Issue by richardebel** [cginternals/globjects#384]
Changed code:
else if (attachmentObject->isRenderBufferAttachment())
    {
        implementation().attachRenderBuffer(this, attachment, nullptr);
    }

To:
else if (attachmentObject->isRenderBufferAttachment())
    {
        implementation().attachRenderBuffer(this, attachment, attachmentObject->asRenderBufferAttachment()->renderBuffer());
    }

**Comment by scheibel** [comment]
Thanks for reporting. I solved the issue by explicitly handling the `nullptr` case. Your solution would not crash but does not detach the renderbuffer either.
